### ISSUE TITLE
Proposal: Observable Streams

### ISSUE THREAD

**Issue by ncthbrt** [aantron/repromise#12]
Node.js's built in streams have awkward semantics which do not fit well into a functional programming paradigm. Observable Streams have much better semantics and at least in theory should be able to accurately capture the behavior of Node's streams. Could have a nice symmetry with promises. If carefully implemented, should only have a small constant additional overhead compared to a naïve interpretation of the bindings. 

Streams are used fairly heavily throughout the node APIs, so it's important that they have a sound foundation.

**Comment by bordoley** [comment]
I working on a general implementation of observable streams for reason, however my underlying goal is to provide a performant isomorphic RX implementation and currently do not plan to support any type of interop to the proposed tc3p observable spec. You can checkout https://github.com/bordoley/rx-reason if you are interested.

**Comment by aantron** [comment]
Closing, as it's probably best done in a separate library. We've also become sensitive to bundle size in Repromise, e.g. https://travis-ci.org/aantron/repromise/jobs/583078509#L244
