### ISSUE TITLE
map may need to have its return value wrapped

### ISSUE THREAD

**Issue by ckknight** [aantron/repromise#15]
`Repromise.resolve(1) |> Repromise.map(x => Repromise.resolve(x + 1))`

In the type system should be `Repromise.promise(Repromise.promise(int))`, but at runtime will ostensibly collapse to `Repromise.promise(int)`.

I believe the way to fix this will be to have separate `map` and `then_` JS functions where `map` makes sure to call `wrap` on the return value of the `callback` provided to `map`, which would prevent the nested resolution.

**Comment by aantron** [comment]
@ckknight Thanks for catching this. I added two test cases based on your example, and the fix is basically what you suggest, but the code has it in Reason syntax rather than JS :) See the attached commit.
