### ISSUE TITLE
Installing in ReasonReact Project

### ISSUE THREAD

**Issue by idkjs** [aantron/repromise#17]
If i have this package.json
```
  "dependencies": {
    "@glennsl/bs-json": "^1.1.2",
    "bs-fetch": "^0.2.1",
    "material-design-icons": "^3.0.1",
    "materialize-css": "^0.100.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "reason-react": "^0.3.2",
    "repromise": "github.com/aantron/repromise"
  },
```
I get this project install in the project: https://github.com/tracker1/repromise. Is that expected?

This syntax  in package.json gets you the correct repo:  "repromise": "github:aantron/repromise"

**Comment by aantron** [comment]
That's not expected/right, and thanks for updating with the right syntax! I'll add the info to the `README` shortly.

I somehow missed the existing `repromise` package in NPM. We will have to rename Repromise if we want to release it standalone, or release it as `reason-repromise`.

However, I think the plan is to upstream the JS parts into BuckleScript as they mature, so I am not sure if we will have a standalone release at all.

**Comment by idkjs** [comment]
I just clicked on your update. I'm getting that I cant use this right now. Is that correct?

**Comment by aantron** [comment]
You can use Repromise. Only the PPX (the `let%await` syntax sugar) will be difficult to use.

You should be able to add `repromise` to `package.json` and `bsconfig.json`, then do `npm install`. After that, your builds should be able to find Repromise. You don't need to use esy, that is for building native code.

You don't need to set `ppx-flags` in `bsconfig.json`, that is only for using the PPX (`lete%await`).

I may set up a sample repo soon.

**Comment by idkjs** [comment]
Thank you, sir.

**Comment by aantron** [comment]
...also, if you really want to use `let%await`, it *is* possible to set it up. I'll probably have to factor it out of this "monorepo" so you can easily reference it using NPM. The reason I didn't do that yet it because it is a slight pain to build anyway, so I figured we will just hide it in this repo until we sort all those things out :)

Please do let me know if you have any trouble :)

**Comment by aantron** [comment]
Example repo here: https://github.com/aantron/repromise-example-bsb.

Also fixed a bug in the development packaging of Repromise that prevented it from being built if you depended on it form outside this repo.

**Comment by idkjs** [comment]
Very helpful, you are, my brother. I will take a look post haste!
