### ISSUE TITLE
New release with all* functions?

### ISSUE THREAD

**Issue by dfalling** [aantron/repromise#41]
Currently the all2, all3... functions are only on master.  Are there plans to push a new release that includes these?

**Comment by aantron** [comment]
Yes, I should be getting a release out soon :) I wanted to also do #40, which I have written the code for, but my local repos were having some bit rot issues with BuckleScript and the test suite that I need to take some time and fix. It doesn't take long, just need a small block of time :)

**Comment by dfalling** [comment]
Great, thanks!

**Comment by aantron** [comment]
All released now as [0.6.1](https://www.npmjs.com/package/@aantron/repromise) :) The changelog is [here](https://github.com/aantron/repromise/releases/tag/0.6.1).
