### ISSUE TITLE
`value instanceof Promise` won't work for promise-likes

### ISSUE THREAD

**Issue by ncthbrt** [aantron/repromise#7]
This wouldn't be wrapped by the current implementation but also collapses:
`Promise.resolve({ then: (res) => res({ then: r => r (5)}) }).then(console.log)`

A suggestion would be to wrap any object containing a `.then` function.

**Comment by aantron** [comment]
Thanks, I believe this is fixed by #9 now. I'm leaving the issue open as a reminder to add a test or tests.

**Comment by ncthbrt** [comment]
I've added some tests
